### ISSUE TITLE
admin view -- order of progress bars

### ISSUE THREAD

**Issue by annefried** [annefried/discanno#1]
doesn't seem to correspond to order of users next to it -- please check

**Comment by JeannedArk** [comment]
Can you provide a screenshot? I did not experience this issue so far. @annefried

**Comment by annefried** [comment]
@JeannedArk , @NicklasLinz , did someone fix this? It looks correct now.

**Comment by JeannedArk** [comment]
Not on purpose maybe as a side effect while fixing other bugs. Then I will close this ticket.
