### ISSUE TITLE
Select Link upon creating on already existing

### ISSUE THREAD

**Issue by NicklasLinz** [annefried/discanno#100]
When dragging between two annotations that are already linked, it is displayed as if a new link was created. That is not the case

**Comment by NicklasLinz** [comment]
Pull request #103

**Comment by annefried** [comment]
fixed in 7644ea0

**Comment by annefried** [comment]
Doesn't work the first time when creating a link.

**Comment by damyana79** [comment]
Link labeling is doesn't always work fine. The message "click to add link" appears but clicking on it doesn't always open the "Annotation"-labels for the links. Often it works only after I've tried it two times or so.
