### ISSUE TITLE
Stretch annotation boxes to make passages larger

### ISSUE THREAD

**Issue by JeannedArk** [annefried/discanno#11]

**Comment by NicklasLinz** [comment]
Began to implement on branch DA-11. It is non trivial. Maybe go for a "Add/Remove word"-Button for ACL, to allow resizing of annotations.

**Comment by NicklasLinz** [comment]
@JeannedArk I would need a "ChangeAnnotation" Rest-Interface to finish this

**Comment by JeannedArk** [comment]
@NicklasLinz REST interface was added (PUT).

**Comment by NicklasLinz** [comment]
Right end of annotations can now be moved with alt+right/alt+left. (On branch DA-11)

**Comment by NicklasLinz** [comment]
ToDo: Text in new line is not highlighted

**Comment by NicklasLinz** [comment]
Implemented on DA-11. Still problems with overlapping annotations. Waiting for feedback from @annefried .

**Comment by annefried** [comment]
Looks nice, and works in Chrome / Firefox on Linux. Are you going to do something about the overlapping annotations?

**Comment by NicklasLinz** [comment]
I plan to do that, but would prioritise the Timeline first

**Comment by annefried** [comment]
I suggest to finish this first, this feature is almost implemented. it sounded to me as if the Timeline might be more work?

**Comment by NicklasLinz** [comment]
Now fixed on DA-11. Please test @JeannedArk  @annefried .

**Comment by annefried** [comment]
Please add hotkeys to list displayed when pressing '?' and make this popup MUCH smaller. @NicklasLinz

**Comment by annefried** [comment]
This happened:
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unq_annotation_0"
  Detail: Key (user_fk, document_fk, targettype_fk, starts, ends)=(1, 232, SituationEntity, 66, 86) already exists.

**Comment by NicklasLinz** [comment]
PR #113

**Comment by NicklasLinz** [comment]
Still problem with multiple Annotations in one line (>2).
