### ISSUE TITLE
Ideas for future developments

### ISSUE THREAD

**Issue by damyana79** [annefried/discanno#118]
We could also write and discuss some ideas about future developments in discanno.
Here are some ideas I gathered by experience or while talking to Anne:
- enable exporting and re-importing of whole already annotated projects and modifying of their annotation schemes
- maybe a second "completed" checkbox at the end of the document or in the menu on the right-hand side so the annotator doesn't have to scroll up the whole text
- maybe specifying, if the type of links in the Graph could also look like undirected.
  (- maybe enabling a "commentary" field for segments marked with categories like "not sure" or "Other")

**Comment by JeannedArk** [comment]
- https://github.com/annefried/discanno/issues/148
- https://github.com/annefried/discanno/issues/149
- 1. https://github.com/annefried/discanno/issues/4   2. https://github.com/annefried/discanno/issues/150
