### ISSUE TITLE
Tooltips for labels in the Annotations window

### ISSUE THREAD

**Issue by SimonOst** [annefried/discanno#119]
When the label name is very long, it is not completely displayed in the annotation window (s. attachment, the ScrPart_in-bath_entertainment). It would be nice if you could implement a tool tip that pops up when hovering over the label and that shows the complete label. This is rather urgent and already confirmed with Anne.
![ex](https://cloud.githubusercontent.com/assets/6973169/14354192/b2c2f95c-fcdc-11e5-88d8-b6fd465fd305.png)

**Comment by NicklasLinz** [comment]
PR #127
