### ISSUE TITLE
Enable Eclipse Support

### ISSUE THREAD

**Issue by NicklasLinz** [annefried/discanno#126]
I personally am in favour of using Eclipse, since it runs much more stable on my machine.
@JeannedArk thinks it is okay to.
What is your opinion @annefried ?

**Comment by NicklasLinz** [comment]
Got it ! :) Will try to reproduce with other machine and then document it.

**Comment by JeannedArk** [comment]
@NicklasLinz current state?

**Comment by JeannedArk** [comment]
Pull request: https://github.com/annefried/discanno/pull/154
