### ISSUE TITLE
Progress bars indicate wrong numbers

### ISSUE THREAD

**Issue by SimonOst** [annefried/discanno#138]
Hi,
when I log in as a project manager to check the progress of some files, the progress bars show faulty numbers. In the screenshot, all bars for simon-ostermann should be empty. The 42 or 10 files that are assigned to simon-ostermann should be assigned to sarahmameche.

Note: I removed the image so that your email addresses etc. are not public :)

**Comment by JeannedArk** [comment]
Pull request: https://github.com/annefried/discanno/pull/140

**Comment by JeannedArk** [comment]
Still not fixed on master

**Comment by JeannedArk** [comment]
@SimonOst Should be fixed now. Haven't noticed any further problems. If you haven't noticed anything the ticket can be closed.

**Comment by JeannedArk** [comment]
I will close the ticket. If there should be any issues in the future the ticket can be reopened.
