### ISSUE TITLE
Graph visualization: ordering of edges left-to-right

### ISSUE THREAD

**Issue by annefried** [annefried/discanno#15]
Display graph more like a left-to-right diagram, e.g., for temporal relations demo. Can we add this as a configurable parameter in the project editor?

**Comment by JeannedArk** [comment]
How exactly should this be realized?
Should this be an extra parameter in the scheme as well? This can only be done with labels which have a predefined semantic. So this cannot be realized if a new LinkLabel is given without any defined semantic. Two possibilities would be:
1. This works only with a few LinkLabels which have already a defined semantic ("before", "after", etc.)
2. You can give LinkLabels an extra parameter which defines the semantic. This would be more flexible, but would mean much more work.

**Comment by annefried** [comment]
Two possibilities:
(a) we create a special scheme & setting for temporal annotations (but we haven't finalized a scheme yet)
(b) all directed edges are displayed left-to-right (this could be a parameter for certain edge types in a later version)

**Comment by JeannedArk** [comment]
- make it dynamically dependent of the box width
- declare Graph/ Timeline in scheme

**Comment by JeannedArk** [comment]
- configure ordering

**Comment by JeannedArk** [comment]
Pull request: https://github.com/annefried/discanno/pull/137
The ordering of the LinkLabels is not implemented yet.

**Comment by JeannedArk** [comment]
TODO adjust wiki and all provided testdata

**Comment by NicklasLinz** [comment]
**Some comments:**

in the editor:
- the positioning of link starts in the timeline is not optimal. it should either be right/left/top/bottom not only left

**Comment by judembo** [comment]
In timeline mode:
![timeline_ordering](https://cloud.githubusercontent.com/assets/19438668/16490572/908aaba6-3eda-11e6-92a0-f3089dd45916.png)

Three horizontal links:
- a -> b
- a -> c
- c  -> b

b and c are ordered vertically, but intuitive would be a horizontal ordering a -> c -> b

**Comment by annefried** [comment]
Seems like we also need right-to-left as an option... is that possible?
