### ISSUE TITLE
Optimize frontend

### ISSUE THREAD

**Issue by JeannedArk** [annefried/discanno#159]
Literature:
- http://archive.oreilly.com/pub/a/server-administration/excerpts/even-faster-websites/writing-efficient-javascript.html#the_switch_statement
- https://developers.google.com/speed/articles/optimizing-javascript#defining-class-methods
- http://desalasworks.com/article/javascript-performance-techniques/

**Comment by NicklasLinz** [comment]
Massive performance improvements for loading large texts.

**Comment by stgrue** [comment]
Too general.
