### ISSUE TITLE
Frontend tests

### ISSUE THREAD

**Issue by JeannedArk** [annefried/discanno#162]
We really need tests for the frontend. I will create some tests with the Jasmine framework. Additionally Selenium tests would be great. Note this is also playground for frontend testing. So other tests can also be written with other frameworks to collect some experience.

Literature:
- http://www.yearofmoo.com/2013/01/full-spectrum-testing-with-angularjs-and-karma.html
- http://de.slideshare.net/fitc_slideshare/unit-testing-front-end-javascript

**Comment by JeannedArk** [comment]
schemeUploadModalController

**Comment by stgrue** [comment]
Will create concrete test issues instead.
