### ISSUE TITLE
Refactoring frontend

### ISSUE THREAD

**Issue by JeannedArk** [annefried/discanno#17]
Refactoring frontend, including make all necessary request async, commenting code, etc.

**Comment by JeannedArk** [comment]
Remove context root: /tempannot in backend + frontend
therefore every request has to be changed
Frameworks like AngularJS should be available as local resources

**Comment by annefried** [comment]
Warnings to be addressed:

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create d3.js:10:2874

**Comment by JeannedArk** [comment]
Rename schemeUploadModal.html (now scheme builder)
signin.js should be a controller and in the controllers folder

**Comment by JeannedArk** [comment]
Maybe a rootController/ baseController is a good idea or renaming the dashboardController to that to make aware that utility functions can be outsourced and reused and to prevent code duplication.

**Comment by NicklasLinz** [comment]
Fixed in a809e

**Comment by JeannedArk** [comment]
What about signin.js (renaming+moving and adding in controllers), renaming dashboardController, tutorialController some refactor comments, working on all refactor related TODOs in frontend?

**Comment by NicklasLinz** [comment]
You are right, it wasn't right to close it. I did only close it, because I did fix the backend queries.

**Comment by JeannedArk** [comment]
This ticket is blocked by: https://github.com/annefried/discanno/issues/152

**Comment by stgrue** [comment]
We will add more concrete issues instead.
