### ISSUE TITLE
Tokenization -- special cases for punctuation in editor

### ISSUE THREAD

**Issue by annefried** [annefried/discanno#18]
eg.
``I
``Lizzy
should not be one token
full stops at the end of a sentence

**Comment by JeannedArk** [comment]
http://nlp.stanford.edu/software/tokenizer.shtml (PTBTokenizer)

**Comment by JeannedArk** [comment]
JavaScript frameworks:
https://docs.marklogic.com/cts:tokenize (you can pass a language parameter)
https://dzone.com/articles/using-natural-nlp-module (https://github.com/NaturalNode/natural#tokenizers)

A list of tokenization tools, but unfortunately no JavaScript framework:
http://tech.grammarly.com/blog/posts/How-to-Split-Sentences.html

Note:
d3AnnotationController $scope.isPunctuation

**Comment by JeannedArk** [comment]
- multiple modi available and in scheme specified?
- as discussed: the processing will be done in backend and sent as an array of arrays, a list containing lists which corresponds to the lines. Each element includes start, end and text.

**Comment by NicklasLinz** [comment]
Implemented in Frontend. Waiting for review by JeannedArk
