### ISSUE TITLE
Performance of editor / asynchronous connection

### ISSUE THREAD

**Issue by annefried** [annefried/discanno#19]
Warnings to be addressed:

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create d3.js:10:2874

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/
--> TODO: make editor asynchronouns, warn user if no connection for > 1 minute (so not many annotations would get lost)

**Comment by annefried** [comment]
see also Christine's email

**Comment by JeannedArk** [comment]
Are these two issues? The second point duplicates this ticket:
https://github.com/annefried/discanno/issues/17

**Comment by JeannedArk** [comment]
No data gets lost. All responses are validated whether the request was successful.

**Comment by annefried** [comment]
Ok, let's track this in #17
