### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by JeannedArk** [annefried/discanno#20]
The README.md file should be updated:
- welcome text, motivation, ...
- screenshots, example pictures
- license
- contributors?
- build status (e.g. https://github.com/duckduckgo/zeroclickinfo-goodies) the build status icon. Realized with https://travis-ci.org/getting_started. Registration can only @annefried do.
- ...

**Comment by JeannedArk** [comment]
@annefried  do you want to be named in contributors with your real name:
https://github.com/annefried/discanno/blob/master/CONTRIBUTING.md ?

**Comment by JeannedArk** [comment]
![Uploading DiscAnno_AnnoTool_1.png…]()

**Comment by JeannedArk** [comment]
![discanno_annotool_1](https://cloud.githubusercontent.com/assets/7132775/13761225/943137e0-ea37-11e5-832e-e129b086f7fa.jpg)

**Comment by JeannedArk** [comment]
<img width="1653" alt="discanno_annotool_2" src="https://cloud.githubusercontent.com/assets/7132775/13761479/2c65b9cc-ea39-11e5-94e1-b401535a552e.png">

**Comment by JeannedArk** [comment]
<img width="1677" alt="discanno_annotool_3" src="https://cloud.githubusercontent.com/assets/7132775/13761517/6ae1a760-ea39-11e5-87b2-142d678464c8.png">

**Comment by JeannedArk** [comment]
<img width="1680" alt="discanno_schemes_2" src="https://cloud.githubusercontent.com/assets/7132775/13761592/dcfb44e6-ea39-11e5-8942-80c7c599d8b5.png">
<img width="799" alt="discanno_schemes_1" src="https://cloud.githubusercontent.com/assets/7132775/13761593/dd23bc0a-ea39-11e5-95e1-fe99c3943630.png">

**Comment by annefried** [comment]
Need to add link to demo.
