### ISSUE TITLE
Misformatted text

### ISSUE THREAD

**Issue by JeannedArk** [annefried/discanno#203]
The following text is not properly displayed. Reported by @damyana79 

![screenshot from 2016-06-07 19 19 53](https://cloud.githubusercontent.com/assets/7132775/15886274/5d5c690c-2d5c-11e6-8bd4-b7c6b99d8906.png)
[lw1.txt](https://github.com/annefried/discanno/files/304230/lw1.txt)

Maybe it is caused by https://github.com/annefried/discanno/issues/143

**Comment by damyana79** [comment]
If it could be of help, I also have another such text:

![screenshot from 2016-06-13 17 03 58](https://cloud.githubusercontent.com/assets/18260513/16012268/03aef402-3189-11e6-8935-108348869a3b.png)

[A_defense_of_Michael_Moore.txt](https://github.com/annefried/discanno/files/312092/A_defense_of_Michael_Moore.txt)

**Comment by stgrue** [comment]
This bug seems to depend on the browser that is being used. It seems not to occur when using Chrome.
