### ISSUE TITLE
Color coding for annotations

### ISSUE THREAD

**Issue by annefried** [annefried/discanno#21]
Configurable:
-- different chains (linked by edges) = different colors (for coreference annotations)
-- different colors for each target types, different shades for each value?

All of this needs some thought and is not urgent.

**Comment by JeannedArk** [comment]
How should annotations be colored with multiple labels: selecting the first label and take that shading, selecting the TargetType color, ...?

**Comment by annefried** [comment]
For now, let's simply choose the color of the first label. We can think of other options later.

**Comment by JeannedArk** [comment]
Approved.
