### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by judembo** [annefried/discanno#234]
Old Logo:
![old_logo_embedded](https://cloud.githubusercontent.com/assets/19438668/16589042/b6b3efc2-42d1-11e6-839d-d1d3ac41218c.png)

New suggestion:
![new_logo_embedded](https://cloud.githubusercontent.com/assets/19438668/16589057/c12679fc-42d1-11e6-87a0-718f3aeb61a9.png)

Please post your feedback or suggestions

**Comment by judembo** [comment]
Two more uppercase suggestions:
![new_logo_embedded2](https://cloud.githubusercontent.com/assets/19438668/16945892/556da3bc-4da7-11e6-8ba7-7906c93b3591.png)

![new_logo_embedded3](https://cloud.githubusercontent.com/assets/19438668/16945898/5b64d4de-4da7-11e6-9557-b61f06769916.png)

And a new version of the old logo, slightly modified so it fits better with the menu bar:
![old_logo_embedded2](https://cloud.githubusercontent.com/assets/19438668/16945938/886f0d32-4da7-11e6-8dba-459aba99ac52.png)

**Comment by JeannedArk** [comment]
![background2](https://cloud.githubusercontent.com/assets/7132775/17945842/dd3cd776-6a45-11e6-81fe-5aeb9eff2654.jpg)
