### ISSUE TITLE
Add more tokenization options

### ISSUE THREAD

**Issue by stgrue** [annefried/discanno#251]
(0. Find out what "unspecified" does)
1. Whitespace
2. Character-wise (chinese)

Also, refactor TokenizationUtil.

**Comment by stgrue** [comment]
1. Whitespace
2. Character-wise (chinese)

**Comment by JeannedArk** [comment]
http://nlp.stanford.edu/nlp/javadoc/javanlp-3.5.2/edu/stanford/nlp/pipeline/TokenizerAnnotator.TokenizerType.html#Unspecified

**Comment by JeannedArk** [comment]
There might be a problem with the spanish tokenization:
[2016-08-10T19:10:10.461+0200] [glassfish 4.1] [SEVERE] [] [] [tid: _ThreadID=31 _ThreadName=Thread-9] [timeMillis: 1470849010461] [levelValue: 1000] [[
  Could not load Spanish data file edu/stanford/nlp/international/spanish/enclitic-inflections.data]]

maybe it appears only on my local machine. If you cannot solve the problem we should remove the spanish tokenization option.

**Comment by stgrue** [comment]
I have not been able to replicate the Spanish bug. I am closing this issue for now.

**Comment by JeannedArk** [comment]
Thought characterwise tokenization does not work?

**Comment by stgrue** [comment]
Reopened.

**Comment by JeannedArk** [comment]
Whats the current status of the characterwise tokenization?

**Comment by stgrue** [comment]
As far as I can tell, it works, but performance is subpar for longer texts. But I think this issue can be closed.
