### ISSUE TITLE
cannot view uploaded text

### ISSUE THREAD

**Issue by damyana79** [annefried/discanno#276]
I am uploading some texts with pre-defined annotation spans and I have problems with only two of these texts. I can upload only the texts but if I try to upload both the texts and the pre-defined spans, I see only empty screen if I want to see the uploaded texts.
I'm sending you the texts and the .json files with the spans (I had to save the json files as .txt and rename them a bit in order to upload them on github, but normally the names of the json file and the corresponding txt have to be the same).

[1401_json.txt](https://github.com/annefried/swan/files/459812/1401_json.txt)
[VOL15_3_json.txt](https://github.com/annefried/swan/files/459813/VOL15_3_json.txt)

[1401.txt](https://github.com/annefried/swan/files/459792/1401.txt)
[VOL15_3.txt](https://github.com/annefried/swan/files/459793/VOL15_3.txt)

**Comment by JeannedArk** [comment]
Thanks, we will have a look!

**Comment by damyana79** [comment]
Hi! Are you also working on the pre-defined spans for annotations? (or should I open a new issue as the problem seems to be a bit different now?) I try to upload the texts with the predefined spans to the new Swan and I get error: that the beginning and end of span don't match. They actually should match, as I was able to upload them last week on the old SWAN. Then I had problem with just two texts. Moreover, the pre-defined spans I have uploaded last week on the old SWAN are now not visible anymore. 
 I also tested uploading a small text to the new SWAN with just one span, for which I was sure it should match too but this also didn't work.
Thanks!

PS: Now I don't get the "spans don't match" error anymore and am able to upload the texts and the spans on the new span. I just am not able to see the texts afterwards. Exact description of the problem follows in the next comment.

**Comment by damyana79** [comment]
I have uploaded 5 texts with target spans to the new SWAN. From these I can see only one. 
I send you one of the texts that I cannot see and the error message:

[1399.txt](https://github.com/annefried/swan/files/469464/1399.txt)

[1399_json.txt](https://github.com/annefried/swan/files/469471/1399_json.txt)

[errorMessage.txt](https://github.com/annefried/swan/files/469472/errorMessage.txt)

And here is the text that somehow works:

[Acephalous-Internet.txt](https://github.com/annefried/swan/files/469475/Acephalous-Internet.txt)

[Acephalous-Internet_json.txt](https://github.com/annefried/swan/files/469477/Acephalous-Internet_json.txt)
