### ISSUE TITLE
Rename user role 'user' to 'annotator'

### ISSUE THREAD

**Issue by JeannedArk** [annefried/discanno#29]
The user role 'user' is not expressive and does not say much about the role. One suggestion would be to rename the role to 'annotator'.
Any opinions @annefried  @NicklasLinz

**Comment by annefried** [comment]
Annotator Sounds fine.

Sent via Xiaomi

**Comment by JeannedArk** [comment]
Note: The user roles have to be changed in the database from 'user' to 'annotator' manually or via script.
