### ISSUE TITLE
Admin annotation view

### ISSUE THREAD

**Issue by JeannedArk** [annefried/discanno#30]
The admin annotation view is still missing. The code already exists, probably in the redmine repository. A (more elegant) updating of the state of the whole page instead of reloading the page is not necessary and therefore and does not cost that much time to implement, but would be a handy feature.

**Comment by JeannedArk** [comment]
Then this ticket can also be closed https://github.com/annefried/discanno/issues/5

**Comment by NicklasLinz** [comment]
A version that reloads the site has been implemented. For dynamic loading a new Issue will be created.

**Comment by JeannedArk** [comment]
The "Users" bar should be hidden as non-'admin'/ 'project manager'.
