### ISSUE TITLE
More structured projects and sorting possibilities

### ISSUE THREAD

**Issue by SimonOst** [annefried/discanno#306]
It would be nice to have a way to give projects a deeper structure. If an annotator works on different tasks for different people, he or she can't easily tell which project belongs to which tasks. Two ways to tackle this might be to either assign tags to projects and then sort projects according to these tags or to give projects a nested structure by adding sub-projects. Then, one "top level project" could have several sub projects, each of which can have their own annotation schema.

Apart from these suggestions, an easier and faster-to-implement way of giving more structure would be the possibility to sort your projects according to the project manager, the name, the level of completeness of the annotations etc. etc.

**Comment by JeannedArk** [comment]
What would suit you more (besides the implementation overhead): tags or a nested project structure?
What would a nested project structure look like: just one kind of "folder" and then just projects or can the projects nest arbitrary more projects (project in project in a project ...)?

**Comment by SimonOst** [comment]
I guess nested projects would be a nicer solution. At least for my purpose (and I think for most other purposes, too) it doesn't have to be recursively nested, one level of sub projects should be sufficient. More levels might be confusing for users (and managers) anyway.

**Comment by JeannedArk** [comment]
And probably additional sorting possibilities would be nice apart from nested projects?

**Comment by SimonOst** [comment]
Yes :)

**Comment by damyana79** [comment]
I think a nice sorting possibility could be "show unsure" view, containing all documents where the annotator marked an item with "unsure" with links to the documents and highlighted "unsure" items inside . This way the annotator and the project manager could keep track of the questions/difficult items inside the tool and discuss them. I don't know, it maybe sounds too complicated/fancy, but if also others find the feature cool, that would be great :)

Bare text view or just a keyboard shortcut for selecting only the text would also be nice. In the moment I have to type the sentences, if I have a question or if I need them as an example to illustrate something.

**Comment by judembo** [comment]
We will add tags

**Comment by judembo** [comment]
Workaround: Use tags in project titels and use existing search functionality
