### ISSUE TITLE
AnnotationTool: After double clicking in the graph annotating not possible

### ISSUE THREAD

**Issue by JeannedArk** [annefried/discanno#32]
After a double click in the graph selecting text and annotating is not possible anymore.

**Comment by NicklasLinz** [comment]
I can not reproduce this. A double click in the graph, on any element, does not stop me from annotating afterwards.

**Comment by JeannedArk** [comment]
(Fortunately) I cannot reproduce this behavior, maybe the updated version of D3 fixed this.
Note: Dragging with a rightclick leads to this behavior for me, but this is a negligible case, realoding the page solves this issue.
