### ISSUE TITLE
Add scrolling when sidebar gets too large

### ISSUE THREAD

**Issue by NicklasLinz** [annefried/discanno#42]
With the addition of Navigation and Users, the sidebar is now to big and might not fit on the screen.

**Comment by JeannedArk** [comment]
Probably the scrollbar broke the format of the sidebar including the Options bar. The radiobuttons, checkboxes are at the wrong place.

**Comment by JeannedArk** [comment]
Move the whole section on the right a few pixels to the right or stretch it so that no horizontal scrollbar appears.
