### ISSUE TITLE
project manager role

### ISSUE THREAD

**Issue by annefried** [annefried/discanno#50]
it looks like the project managers can also annotate. They should have the same view of the editor as the admin. please check

**Comment by annefried** [comment]
The buttons in the Annotations view should be completely inactive for project managers (but colored the way the respective selected annotators marked them).

**Comment by JeannedArk** [comment]
I imagine you mean the "Annotations" section in the annotation tool?

**Comment by annefried** [comment]
Yes.

**Comment by annefried** [comment]
Admins and project managers can use the editor: annotations that they create do not seem to be saved, but when they change labels for annotations created by an annotator, the respective annotator's data seems to be changed in database. IMPORTANT: only annotators should be allowed to use the editor!
(a) text editor should not be editable for non-annotators @NicklasLinz 
(b) annotation options should not be editable for non-annotators

**Comment by annefried** [comment]
Fixed part (b) of the problem, which has the effect that (a) is not so bad: all admins & project managers can do now is to select a span, but they can't assign a type and thus they can never create an annotation. We could even consider leaving this as it is for now.

**Comment by annefried** [comment]
PR #85

**Comment by JeannedArk** [comment]
The ticket can be closed?

**Comment by annefried** [comment]
No, I just noticed that this workaround does not work when there is only target type. In that case, project managers can still create annotations. Please deactivate this completely (when selecting a new span in the text editor, it should be checked whether user is an annotator before creating an annotation).

**Comment by JeannedArk** [comment]
Pull request: https://github.com/annefried/discanno/pull/92
