### ISSUE TITLE
Add loading wheel when opening editor

### ISSUE THREAD

**Issue by NicklasLinz** [annefried/discanno#51]
Because it takes some time for a document to load users might be confused if they clicked on the view button. The loading wheel would help.

**Comment by JeannedArk** [comment]
Quick solution: checking document size then add alert.

**Comment by JeannedArk** [comment]
Did not find an async solution. A better solution could be showing the alert before the page is supposed to be opened.

**Comment by NicklasLinz** [comment]
PR #114
