### ISSUE TITLE
Development setup

### ISSUE THREAD

**Issue by annefried** [annefried/discanno#53]
- glassfish-resources.xml still has TempAnnot.
- update default admin user + password in README, id should be 0 as system seems to start counting at 1

**Comment by JeannedArk** [comment]
- The change from TempAnnot to DiscAnno has still to be done, but therefore we have to change the database as well, because the current db is named TempAnnot.
- the id counting does not really matter, the db takes care of it. The can also be increased in steps of 200.

**Comment by annefried** [comment]
I mean if you set it up for the first time -- you get an error otherwise because user with id 1 already exists

**Comment by JeannedArk** [comment]
This ticket is about the README.md (preview on the start page of the project)?
The second point was about these two lines if I understood you right:
INSERT INTO users (id, createdate, email, lastname, password, prename, role)
    VALUES (1, 2016-01-22 22:23:08.25, admin@web.de, Doe, -2d8bd2605ef266f054a2b774af60ffdd9534c9edec5cba71, John, admin);

The first time you run the project, there should be no entries in the db, therefore no duplicate key error should appear.

**Comment by annefried** [comment]
right, we need to omit id from these lines or set it to 0. Otherwise the first time you try creating a user via the interface, it won't work (and it doesn't give you an error message in the system, duplicate key error occurs)

**Comment by annefried** [comment]
Tried it today, works.
