### ISSUE TITLE
links: selection and creation

### ISSUE THREAD

**Issue by annefried** [annefried/discanno#54]
add boxes around link labels to allow for easier selection
after creating a link, focus on the link, load Options for link labels (currently the start/end node is focused instead)

**Comment by JeannedArk** [comment]
Focusing the created link is already on master

**Comment by annefried** [comment]
Link is focused, but the annotation / label options are not shown in the Annotations box. Please fix @NicklasLinz

**Comment by NicklasLinz** [comment]
I can not reproduce this. For me they are displayed

**Comment by annefried** [comment]
browser refresh issue.

**Comment by annefried** [comment]
Damyana / Simon: Link labeling is doesn't always work fine. The message "click to add link" appears but clicking on it doesn't always open the "Annotation"-labels for the links. Often it works only after I've tried it two times or so.

**Comment by annefried** [comment]
does not happen if nodes are new, only if there are already links starting/ending there

**Comment by SimonOst** [comment]
> Link is focused, but the annotation / label options are not shown in the Annotations box. 

This bug still occurs if linking two spans that are **labelled.** If the spans are not labelled, the label options are shown immediately after drawing the link.

**Comment by JeannedArk** [comment]
Pull request: https://github.com/annefried/discanno/pull/133
