### ISSUE TITLE
Reduce unnecessary data in JSONs

### ISSUE THREAD

**Issue by JeannedArk** [annefried/discanno#56]
e.g. the text in document

**Comment by JeannedArk** [comment]
Wait for testing of @NicklasLinz

**Comment by NicklasLinz** [comment]
Can't really tell if it is faster. There are still too many requests from the Frontend. I will try to fix this.

**Comment by JeannedArk** [comment]
Stable or not? Locally with my version (one project, 10 documents) the projects JSON decreased from 61kb to 2,5kb and the documentById request in the annotation tool is removed.
for frontend improvement open a new ticket please

**Comment by JeannedArk** [comment]
There is already one still open https://github.com/annefried/discanno/issues/17

**Comment by NicklasLinz** [comment]
It is stable. Since rendering takes longer than the actual loading you do not notice the change.
