### ISSUE TITLE
Annotation options design

### ISSUE THREAD

**Issue by annefried** [annefried/discanno#62]
Improving graphical design for selection of labels / links.

**Comment by annefried** [comment]
Tested for Chrome & Firefox on ubuntu. Please check on other OS & browsers as well.

**Comment by NicklasLinz** [comment]
It is working on OSX with Chrome and Firefox.
In my opinion, the buttons for Target Types and Labels are a bit to bulky right now. Maybe we could make them slimmer, add a minimal margin in between them and make them all the same length? Opinions? @annefried @JeannedArk

**Comment by NicklasLinz** [comment]
This would be the direction I want to go in:
![vorschlag](https://cloud.githubusercontent.com/assets/13366276/13967240/69e63e6e-f076-11e5-9506-737e388d0f54.png)

**Comment by JeannedArk** [comment]
We have to remove the console logging:
clicked on: verb
called add label sets

**Comment by JeannedArk** [comment]
It is possible to set a marked section as "not sure" (no annotation). This leads to an error.

**Comment by annefried** [comment]
Disabled the checkbox if no target type is selected. However, this error should also be caught in the backend.

**Comment by annefried** [comment]
Changed CSS. We need a good idea how to display whether one or multiple buttons may be selected (in the future).

**Comment by annefried** [comment]
fixed in master a09122

**Comment by annefried** [comment]
Need to do something about long labels. Can we change the column design to be more flexible?

**Comment by annefried** [comment]
@NicklasLinz @JeannedArk please check / close issue

**Comment by JeannedArk** [comment]
We can close it?
