### ISSUE TITLE
Targets are not displayed

### ISSUE THREAD

**Issue by JeannedArk** [annefried/discanno#65]
Targets are not displayed on the VM, simono reported that issue.

**Comment by NicklasLinz** [comment]
Found the problem. No user_fk is added when uploading targets. Should be handled like document states

**Comment by JeannedArk** [comment]
The defaultAnnotation/ targets belonging to the original document have no user, that's the desired behavior. Additionally with every add user oder documents with targets they are generated for each user and there the user is set. It works locally on my machine on master, maybe the VM is too outdated.

Updating the VM then reporting.
