### ISSUE TITLE
Check consistency of target types in target files with those defined in the scheme

### ISSUE THREAD

**Issue by NicklasLinz** [annefried/discanno#68]

**Comment by JeannedArk** [comment]
Pull request: https://github.com/annefried/discanno/pull/76

**Comment by JeannedArk** [comment]
Pull request https://github.com/annefried/discanno/pull/77

**Comment by annefried** [comment]
couldn't get this to work yet, see comments in pull request

**Comment by annefried** [comment]
This issue relates to start / end type of links WITHIN schemes for upload (not upload of documents with predefined annotation targets).

**Comment by JeannedArk** [comment]
and the "appliesToTargetTypes" of LabelSets
I will fix the uploadable targets later
