### ISSUE TITLE
Scheme deletion

### ISSUE THREAD

**Issue by annefried** [annefried/discanno#69]
- after a scheme is not used in any project any more, the red button gets enabled, but the scheme cannot be delete. the error message is not informative ("no connection to server")
  @JeannedArk @NicklasLinz please take a look.

**Comment by annefried** [comment]
Project managers should not be able to delete schemes created by other users. Can we save the information who created a scheme and only allow this user (and admins) to delete this scheme?

**Comment by annefried** [comment]
side note: It's ok if project managers see the schemes created by other users and can create copies of it.

**Comment by JeannedArk** [comment]
Pull request https://github.com/annefried/discanno/pull/73
