### ISSUE TITLE
change terminology in frontend

### ISSUE THREAD

**Issue by annefried** [annefried/discanno#88]
user --> annotator

**Comment by annefried** [comment]
targets? annotations? labels?

**Comment by JeannedArk** [comment]
Where exactly should they be renamed? The "Users" page e.g. also includes admins and project managers

**Comment by annefried** [comment]
e.g. in the Projects table: "users" lists the "annotators" for the project. Also in the modal when assigning annotators to a project, I think. I can also take care of this issue on Monday.

**Comment by annefried** [comment]
PR88
