### ISSUE TITLE
selection of spans in editor sometimes "stuck"

### ISSUE THREAD

**Issue by annefried** [annefried/discanno#89]
works again after selecting some other area -- @NicklasLinz  suggested something is wrong with the focus of the browser, can we do something about it?

**Comment by NicklasLinz** [comment]
@annefried @JeannedArk I have a really hard time reproducing this.

**Comment by NicklasLinz** [comment]
PR #112 @annefried

**Comment by annefried** [comment]
fixed in cbef996
