### ISSUE TITLE
add error message if  uploaded predefined spans don't start/end at token

### ISSUE THREAD

**Issue by annefried** [annefried/discanno#98]
otherwise, they are not displayed for annotators in some cases!

**Comment by damyana79** [comment]
There may be not displayed tokens especially if the beginning doesn't coincide with the beginning of a word.

**Comment by annefried** [comment]
And please also disable submit button in documentUploadModal if targets only are given, but no matching filename. at the moment the modal closes without an error message; nothing is added

**Comment by JeannedArk** [comment]
Added backendside check, @NicklasLinz has to fix post request error handling in $scope.submit in the documentAddModalController. I added iraqInvalid with invalid spans and it threw an exception as expected. The function submit does not catch an error in the request.
